//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PracticeTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!
        ///Hello, World!
        ///Hello, World!
        ///Hello, World!
        ///Hello, World!
        ///Hello, World!.
        /// </summary>
        public static string Task1Test1 {
            get {
                return ResourceManager.GetString("Task1Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Task1Test2 {
            get {
                object obj = ResourceManager.GetObject("Task1Test2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Task1Test3 {
            get {
                object obj = ResourceManager.GetObject("Task1Test3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a, 0.24, 24
        ///aa, 0.18, 18
        ///second, 0.09, 9
        ///девятый, 0.09, 9
        ///b, 0.09, 9
        ///third, 0.06, 6
        ///fifth, 0.06, 6
        ///tenth, 0.06, 6
        ///first, 0.03, 3
        ///fourth, 0.03, 3
        ///sixth, 0.03, 3
        ///seveth, 0.03, 3
        ///восьмой, 0.03, 3
        ///.
        /// </summary>
        public static string Task1Test4Result {
            get {
                return ResourceManager.GetString("Task1Test4Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first second third
        ///second second third fourth
        ///fifth
        ///fifth
        ///sixth seveth
        ///восьмой
        ///
        ///девятый девятый девятый
        ///tenth tenth
        ///a a a a a aa
        ///a, a, a,aa
        ///aa!aa!aa!aa!
        ///b-b-b.
        /// </summary>
        public static string Task1Test4Source {
            get {
                return ResourceManager.GetString("Task1Test4Source", resourceCulture);
            }
        }
    }
}
