//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.TasksLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.TasksLibrary.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command push on stack only one value.
        /// </summary>
        internal static string Exception_CommandPushOnStackOnlyOne {
            get {
                return ResourceManager.GetString("Exception_CommandPushOnStackOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command should have parameter.
        /// </summary>
        internal static string Exception_CommandShouldHaveParameter {
            get {
                return ResourceManager.GetString("Exception_CommandShouldHaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command shouldn&apos;t have parameters.
        /// </summary>
        internal static string Exception_CommandShouldntHaveParameters {
            get {
                return ResourceManager.GetString("Exception_CommandShouldntHaveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Define command contains an incorrect parameter.
        /// </summary>
        internal static string Exception_DefineCantParseValue {
            get {
                return ResourceManager.GetString("Exception_DefineCantParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Define command should contain two parameters.
        /// </summary>
        internal static string Exception_IncorrectAmountForDefineCommand {
            get {
                return ResourceManager.GetString("Exception_IncorrectAmountForDefineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack is empty.
        /// </summary>
        internal static string Exception_StackIsEmpty {
            get {
                return ResourceManager.GetString("Exception_StackIsEmpty", resourceCulture);
            }
        }
    }
}
